apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
      namespace: system
    patch: |-
      - op: replace
        path: /spec/template/spec/securityContext
        value: null
